// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"service/yang/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/chabai/v1",
				Handler: ComeHandler(serverCtx),
			},
		},
	)
}
